name: Chator Client - Nightly Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Publish Docker Image to Chator - Nightly - Latest Tag
      uses: VaultVulp/gp-docker-action@1.1.2
      with:
        # GitHub token to push Docker image to GitHub Packages
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Docker Image name
        image-name: ChatorClient-Nightly
        image-tag: latest
        dockerfile: Dockerfile
        build-context: .
